---
language: php

# addons:
  # apt:
    # packages:
    # - elinks # For dysplaying php files on console.
    # - empty-expect

cache:
  directories:
  - $HOME/.composer/cache/files

php:
# - nightly
- 7.2 # For Drupal 8.5+
# - 7.1 # Recommanded for Drupal 8.4
# - 7.0 # Debian 9
# - 5.6 # Minimum for Drush 9, Debian 8
# - 5.5 # Minimum for Drupal 8

# services:
# - mysql
# - postgresql

env:
  global:
  - DRUPAL_DEV_VERSION="8.6.x-dev"
  # - DRUPAL_DEV_VERSION="^8.5@alpha"
  # - PATH=$TRAVIS_BUILD_DIR:~/.composer/vendor/bin:$(pwd)/$DRUPAL_PROJECT_DIR/vendor/bin:$PATH # $(pwd) for bash source commands and files.

before_install:
- if [ -f /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then phpenv config-rm xdebug.ini; fi
# - composer global require --dev sensiolabs/security-checker
# - composer create-project symfony/skeleton ~

# - pip install pygments # but now pygmentize is no more used right here.
- go get -u github.com/jingweno/ccat

install:
# - bash composer_create_drupal-project.bash
- composer create-project --no-install symfony/skeleton $DRUPAL_PROJECT_DIR $SKELETON_VERSION
- if [[ -v $DRUPAL_PROJECT_DIR ]]; then cd $DRUPAL_PROJECT_DIR; else cd skeleton; fi;

- cp composer.json ~
- pushd ~
- composer install
- composer require security-checker
- popd

- composer install
- composer require security-checker
- composer require drupal/core

before_script:

script:
# - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock 2 times
- cd ..
# - if [[ -v $DRUPAL_PROJECT_DIR ]]; then rm -rf $DRUPAL_PROJECT_DIR; else rm -rf drupal-project; fi;
# - bash demo_standard.bash --server-bypass

# - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock ~/.composer/composer.lock
# - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@${USER}/.composer/composer.lock'
#^ This checks that the application doesn't use dependencies with known security vulnerabilities

after_script:
- composer show
- composer show --latest
- composer show --tree
# - composer why --tree phpunit/phpunit
# - composer why --tree symfony/http-kernel
- $GOPATH/bin/ccat composer.json
# - ls --color web/profiles
# - ls --color web/core/profiles
